# CI docker publish
#
# version 1.0.0
#
# see : https://universe.fugerit.org/src/docs/conventions/workflows/docker_publish.html

name: CI docker publish

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - develop
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Echo ref name trigger
        run: echo ${{ github.ref_name }}
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@main
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/setup-node@main
        with:
          node-version: 20
      - name: Build main project
        run: mvn -B clean install -P full,coverage,metadata,buildreact
      - name: Build quarkus project
        run: cd fj-doc-playground-quarkus;mvn -B clean install -P full,coverage,metadata,buildreact
          # using action https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: fj-doc-playground-quarkus
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fugeritorg/fj-doc-playground-quarkus:${{ github.ref_name }},fugeritorg/fj-doc-playground-quarkus:latest